Docs/how to use the solution
microsoft/Broadcast-Development-Kit pull request #10
Opened 2021-08-05 17:34 UTC by nelsonsouthworks

## Purpose
Explain how to operate the Broadcast Development Kit (BDK) through the Backend solution.

2021-08-05 18:01 UTC, sw-dcherubini requested changes
We should add a link to this document in the main README of the repository.

2021-08-05 19:48 UTC, facundoctes commented on docs/how-to-use-the-solution/README.md
> +### Client Credential Flow
What do you think about linking to the Microsoft documentation where it explains both flows?

2021-08-05 20:31 UTC, sw-dcherubini commented on docs/how-to-use-the-solution/README.md
> +### Client Credential Flow
@facundoctes Yes, that might be enough.

2021-08-05 21:06 UTC, sw-dcherubini requested changes
Looks like we are missing the API endpoint to change / regenerate the RTMP stream key.

2021-08-06 16:39 UTC, sw-dcherubini requested changes

2021-08-06 16:39 UTC, sw-dcherubini commented on docs/how-to-use-the-solution/README.md
> +1. **Generate RTMP Stream Key:** This endpoint updates the streamKey in the privateContext of the call, used key for RTMP  injections and extractions.
**nitpick**: We have a double white-space between "RTMP" and "injections". Also lets add a sentence here saying that you only need to use the endpoint if you want to change the RMTP key of the current meeting, and that each meeting has its own RTMP key.

2021-08-06 16:39 UTC, sw-dcherubini commented on docs/how-to-use-the-solution/README.md
> +        "resourceType": "{{resourceType}}",
**suggestion (blocking)**: The problem with putting these placeholders in double quotes, is that these properties don't expect an string. By putting the double quotes here we are giving the impression the value should be an string.

Instead, lets put an example value and refer to the property name in reference table. E.g.:
```json
{
    "protocol": 1
}
```
| Placeholder | Description |
|-------------|-------------|
| protocol | Use `1` for RTMP extraction protocol |

2021-08-06 18:47 UTC, sw-dcherubini approved these changes

2021-08-06 18:51 UTC, merged